services:
  netease:
    name: "网易云音乐"
    enabled: true
    domains:
      - "music.163.com"
      - "interface.music.163.com"
      - "interface3.music.163.com"
      - "api.music.163.com"
      - "mam.netease.com"
      - "clientlog.music.163.com"
      - "httpdns.n.netease.com"
      - "163.com"
    features:
      extract_cookie:
        enabled: true
        interval: 3600  # 1 Hour
        output_file: "data/outputs/netease/cookie.json"
        format: "netease_auth"
      extract_playlist:
        enabled: true
        target_ids:
          - "9951570527"  # 可配置多个目标播放列表ID
        output_dir: "data/outputs/netease/playlists"
        save_format: "json"
        
  quark:
    name: "夸克网盘"
    enabled: true
    domains:
      - "pan.quark.cn"
      - "drive-pc.quark.cn"
      - "drive-h.quark.cn"
    features:
      extract_cookie:
        enabled: true
        interval: 7200  # 2小时
        output_file: "data/outputs/quark/cookie.json"
        format: "standard"
    
  # 示例：可以轻松添加新服务
  # bilibili:
  #   name: "哔哩哔哩"
  #   enabled: false
  #   domains:
  #     - "bilibili.com"
  #     - "api.bilibili.com"
  #     - "passport.bilibili.com"
  #   extract_interval: 3600  # 1小时
  #   output_file: "data/outputs/bilibili_cookie.json"
  #   cookie_format: "standard"