# sync_music 配置文件
# 音乐同步工具配置

# =============================================================================
# 目录配置 - 必须配置
# =============================================================================

# 用户音乐目录：存放已有音乐文件的目录
# 支持环境变量，如 $HOME/Music 或 %USERPROFILE%\Music
# 可以是单个目录（字符串）或多个目录（列表）
user_dir: 
  - Z:\网易音乐源文件
  - Z:\网易音乐已解锁
# 或者使用单个目录：
# user_dir: ~/Music

# 输入音乐目录：存放待处理音乐文件的目录（格式：id-bitrate-hash.mp3）
input_dir: C:\Users\Jagger\AppData\Local\NetEase\CloudMusic\Cache\Cache

# 输出音乐目录：复制和重命名后的音乐文件存放目录
output_dir: "\\\\TARS\\Music\\music_sync"

# =============================================================================
# JSON文件配置
# =============================================================================

# 单个播放列表JSON文件路径（可选，命令行参数优先）
json_file: ./data/outputs/netease/playlists/playlist_9951570527.json

# 包含多个JSON文件的目录路径
# json_dir: ./playlists

# =============================================================================
# 数据库配置
# =============================================================================

# 数据库文件路径
database_path: "\\\\TARS\\Music\\music_sync.db"

# 完整数据库URL（可选，如果设置则忽略database_path）
# 示例：sqlite:///path/to/database.db
# 示例：postgresql://user:pass@localhost/dbname
# database_url: null

# =============================================================================
# 文件处理配置
# =============================================================================

# 支持的音频文件扩展名
supported_extensions:
  - .mp3
  - .flac

# 是否优先选择最高码率的文件
max_bitrate_preference: true

# 是否复制文件（false则只创建符号链接，Windows下可能需要管理员权限）
copy_files: true

# 是否覆盖已存在的文件
overwrite_existing: false

# =============================================================================
# 输出和日志配置
# =============================================================================

# 详细输出模式
verbose: true

# 是否显示进度信息
show_progress: true

# 日志级别：DEBUG, INFO, WARNING, ERROR
log_level: INFO

# =============================================================================
# 高级配置
# =============================================================================

# 是否启用文件hash计算
enable_file_hash: true

# 是否启用码率提取（需要mutagen库）
enable_bitrate_extraction: true

# 批处理大小
batch_size: 100

# 最大工作线程数
max_workers: 4

# =============================================================================
# 示例配置（Windows）
# =============================================================================
# user_dir: C:/Users/%USERNAME%/Music
# input_dir: D:/MusicInput
# output_dir: D:/MusicOutput
# json_dir: C:/Users/%USERNAME%/Documents/Playlists

# =============================================================================
# 示例配置（Linux/macOS）
# =============================================================================
# user_dir: $HOME/Music
# input_dir: /data/music_input
# output_dir: /data/music_output  
# json_dir: $HOME/Documents/playlists